name: Prod deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'Kritskii-A/react-keycloak'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      # - run: npm run build
      - name: 'NPM Identity'
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - name: 'Publish'
        run: |
          npx lerna publish from-package --no-verify-access --yes --force-publish
      # - name: Create a new GitHub release
      #   run: |
      #     echo ${{ secrets.TOKEN_GITHUB }} > nothing.md
      #     gh auth login --with-token < nothing.md
      #     gh release create ${{ env.CURRENT_VERSION }} -F README.md -t "Released ${{ env.CURRENT_VERSION }}"
      - name: Prepare static files for deployment
        run: npm run static
