name: Prod deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: github.repository == 'Kritskii-A/react-keycloak'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
      - name: Publish package to NPM registry
        env:
          NPM_AUTH_TOKEN: ${{ secrets.TOKEN_NPM }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
          npm whoami
          npm run release

      # - name: Create a new GitHub release
      #   run: |
      #     echo ${{ secrets.TOKEN_GITHUB }} > nothing.md
      #     gh auth login --with-token < nothing.md
      #     gh release create ${{ env.CURRENT_VERSION }} -F README.md -t "Released ${{ env.CURRENT_VERSION }}"
      - name: Prepare static files for deployment
        run: npm run static
